[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.20.7"
  NPM_VERSION = "10.8.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 